// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeUfsG0jEsY-z1rBAkAoKe474mbfmQ70s',
    appId: '1:221217227974:web:34c644479f89b7e7ea03c7',
    messagingSenderId: '221217227974',
    projectId: 'smart-locker-project-45bac',
    authDomain: 'smart-locker-project-45bac.firebaseapp.com',
    storageBucket: 'smart-locker-project-45bac.firebasestorage.app',
    measurementId: 'G-Q46VYW3VKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfSI9o1gQqhOb11Vz8Fem5T4Iuyl-zxGk',
    appId: '1:221217227974:android:ceb12390b5634da0ea03c7',
    messagingSenderId: '221217227974',
    projectId: 'smart-locker-project-45bac',
    storageBucket: 'smart-locker-project-45bac.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMYj5LX98TYVzsEOLty8LO0W0sNYWdN4',
    appId: '1:221217227974:ios:5f0e27984f350d34ea03c7',
    messagingSenderId: '221217227974',
    projectId: 'smart-locker-project-45bac',
    storageBucket: 'smart-locker-project-45bac.firebasestorage.app',
    iosBundleId: 'com.smartlocker.mprojectapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIMYj5LX98TYVzsEOLty8LO0W0sNYWdN4',
    appId: '1:221217227974:ios:5f0e27984f350d34ea03c7',
    messagingSenderId: '221217227974',
    projectId: 'smart-locker-project-45bac',
    storageBucket: 'smart-locker-project-45bac.firebasestorage.app',
    iosBundleId: 'com.smartlocker.mprojectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeUfsG0jEsY-z1rBAkAoKe474mbfmQ70s',
    appId: '1:221217227974:web:a916d7db8c84809aea03c7',
    messagingSenderId: '221217227974',
    projectId: 'smart-locker-project-45bac',
    authDomain: 'smart-locker-project-45bac.firebaseapp.com',
    storageBucket: 'smart-locker-project-45bac.firebasestorage.app',
    measurementId: 'G-X2CB4BJV5X',
  );
}
