[env:esp32dev]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    adafruit/Adafruit GFX Library @ ^1.11.11
    ricmoo/QRCode @ ^0.0.1
build_flags =
    -D CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=16384
    -D CORE_DEBUG_LEVEL=0
    -D CONFIG_ESP_TASK_WDT_EN=y